"""
Sample test data for Phase 3 integration testing.
Contains realistic chunks and facts for Navi AMC schemes.
"""

# Sample chunks that would be generated by Phase 2
SAMPLE_CHUNKS = [
    {
        "chunk_id": "navi_amc_overview_001",
        "source_id": "groww_navi_amc",
        "url": "https://groww.in/mutual-funds/amc/navi-mutual-funds",
        "fetched_at": "2026-03-05T10:30:00Z",
        "section_path": "Overview",
        "chunk_type": "narrative",
        "text": "Navi Mutual Fund is a SEBI-registered mutual fund with AUM of INR 9,102.56 Cr. as of March 2026. The fund house offers various schemes including equity, debt, and hybrid funds.",
        "fields_present": ["aum", "fund_size_aum"],
        "token_count": 45
    },
    {
        "chunk_id": "navi_amc_facts_001",
        "source_id": "groww_navi_amc",
        "url": "https://groww.in/mutual-funds/amc/navi-mutual-funds",
        "fetched_at": "2026-03-05T10:30:00Z",
        "section_path": "Key Facts",
        "chunk_type": "typed_fact",
        "text": "AUM: INR 9,102.56 Cr",
        "fields_present": ["fund_size_aum"],
        "token_count": 8
    },
    {
        "chunk_id": "navi_flexi_cap_001",
        "source_id": "groww_scheme_navi_flexi_cap",
        "url": "https://groww.in/mutual-funds/navi-flexi-cap-fund",
        "fetched_at": "2026-03-05T10:30:00Z",
        "section_path": "Scheme Details",
        "chunk_type": "typed_fact",
        "text": "Minimum SIP: INR 100, Minimum Lumpsum: INR 5000, Expense Ratio: 0.35%",
        "fields_present": ["min_sip", "min_lumpsum", "expense_ratio"],
        "token_count": 15
    },
    {
        "chunk_id": "navi_elss_tax_saver_001",
        "source_id": "groww_scheme_navi_elss_tax_saver",
        "url": "https://groww.in/mutual-funds/navi-elss-tax-saver-fund",
        "fetched_at": "2026-03-05T10:30:00Z",
        "section_path": "Scheme Details",
        "chunk_type": "typed_fact",
        "text": "Minimum SIP: INR 500, Minimum Lumpsum: INR 500, Lock-in Period: 3 years, Expense Ratio: 0.32%",
        "fields_present": ["min_sip", "min_lumpsum", "lock_in", "expense_ratio"],
        "token_count": 18
    },
    {
        "chunk_id": "amfi_nav_explanation_001",
        "source_id": "amfi_nav",
        "url": "https://www.amfiindia.com/investor-corner/knowledge-center/what-is-nav",
        "fetched_at": "2026-03-05T10:30:00Z",
        "section_path": "NAV Explanation",
        "chunk_type": "narrative",
        "text": "NAV or Net Asset Value is the market value of all assets held by the scheme minus its liabilities, divided by the number of units outstanding. NAV changes daily based on market movements.",
        "fields_present": [],
        "token_count": 38
    },
    {
        "chunk_id": "amfi_expense_ratio_001",
        "source_id": "amfi_expense_ratio",
        "url": "https://www.amfiindia.com/investor-corner/knowledge-center/expense-ratio",
        "fetched_at": "2026-03-05T10:30:00Z",
        "section_path": "Expense Ratio",
        "chunk_type": "narrative",
        "text": "Expense ratio is the annual fee charged by mutual funds to cover operational costs. It is expressed as a percentage of the fund's assets under management.",
        "fields_present": [],
        "token_count": 32
    },
    {
        "chunk_id": "navi_large_midcap_001",
        "source_id": "groww_scheme_navi_large_midcap",
        "url": "https://groww.in/mutual-funds/navi-large-midcap-fund",
        "fetched_at": "2026-03-05T10:30:00Z",
        "section_path": "Scheme Details",
        "chunk_type": "typed_fact",
        "text": "Minimum SIP: INR 100, Minimum Lumpsum: INR 100, Expense Ratio: 0.34%, Risk Level: High",
        "fields_present": ["min_sip", "min_lumpsum", "expense_ratio", "risk_label"],
        "token_count": 16
    }
]

# Expected responses for test queries
EXPECTED_RESPONSES = {
    "what is the AUM of Navi AMC?": {
        "answer": "INR 9,102.56 Cr",
        "source_url": "https://groww.in/mutual-funds/amc/navi-mutual-funds",
        "query_type": "numeric",
        "field": "fund_size_aum"
    },
    "what is the minimum SIP for Navi Flexi Cap?": {
        "answer": "INR 100",
        "source_url": "https://groww.in/mutual-funds/navi-flexi-cap-fund",
        "query_type": "numeric",
        "field": "min_sip"
    },
    "what is NAV?": {
        "answer": "NAV or Net Asset Value is the market value of all assets held by the scheme minus its liabilities, divided by the number of units outstanding.",
        "source_url": "https://www.amfiindia.com/investor-corner/knowledge-center/what-is-nav",
        "query_type": "educational"
    },
    "what is expense ratio?": {
        "answer": "Expense ratio is the annual fee charged by mutual funds to cover operational costs. It is expressed as a percentage of the fund's assets under management.",
        "source_url": "https://www.amfiindia.com/investor-corner/knowledge-center/expense-ratio",
        "query_type": "educational"
    },
    "what is the lock-in period for Navi ELSS Tax Saver?": {
        "answer": "3 years",
        "source_url": "https://groww.in/mutual-funds/navi-elss-tax-saver-fund",
        "query_type": "numeric",
        "field": "lock_in"
    }
}

# Test queries with expected results
TEST_QUERIES = [
    {
        "query": "what is the AUM of Navi AMC?",
        "expected_answer_contains": ["9,102.56", "INR"],
        "expected_url": "https://groww.in/mutual-funds/amc/navi-mutual-funds",
        "query_type": "numeric"
    },
    {
        "query": "what is NAV?",
        "expected_answer_contains": ["Net Asset Value", "assets", "liabilities"],
        "expected_url": "https://www.amfiindia.com/investor-corner/knowledge-center/what-is-nav",
        "query_type": "educational"
    },
    {
        "query": "what is the minimum SIP for Navi Flexi Cap?",
        "expected_answer_contains": ["100", "INR"],
        "expected_url": "https://groww.in/mutual-funds/navi-flexi-cap-fund",
        "query_type": "numeric"
    },
    {
        "query": "what is expense ratio?",
        "expected_answer_contains": ["annual fee", "operational costs"],
        "expected_url": "https://www.amfiindia.com/investor-corner/knowledge-center/expense-ratio",
        "query_type": "educational"
    },
    {
        "query": "tell me about Navi mutual funds",
        "expected_answer_contains": ["SEBI", "AUM", "schemes"],
        "expected_url": "https://groww.in/mutual-funds/amc/navi-mutual-funds",
        "query_type": "factual"
    },
    {
        "query": "what is the lock-in period for ELSS?",
        "expected_answer_contains": ["3 years", "lock-in"],
        "expected_url": "https://groww.in/mutual-funds/navi-elss-tax-saver-fund",
        "query_type": "numeric"
    }
]